//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PublixLibrary
    {
        public string Title { get; set; }
        public string Author { get; set; }
        public decimal Price { get; set; }
        public string Publisher { get; set; }
        public System.DateTime AddedON { get; set; }
        public int Id { get; set; }
    }
}
